languageCode = "en"
languageName = "English"
weight = 2
title = "@zozores"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2 2006"
  description = "Personal site of Thiago (Zozô) Ozores"
  copyright = "© 2025 Thiago (Zozô) Ozores - <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">CC BY-NC-SA 4.0</a>"

[params.author]
  name = "Thiago (Zozô) Ozores"
  headline = "Staff SRE | Teacher | Scout"
  bio = "Staff SRE | Teacher | Scout"
  image = "img/courage.jpg"
  links = [
    { linkedin = "https://www.linkedin.com/in/tozores" },
    { github = "https://github.com/zozores" },
    { gitlab = "https://gitlab.com/zozores" },
    { codeberg = "https://codeberg.org/zozores" },
    { bluesky = "https://bsky.app/profile/zozor.es" },
    { mastodon = "https://social.zozo.pro.br/@zozo" },
    { dev = "https://dev.to/zozores" },
  ]