[[main]]
name = "Artigos"
pageRef = "articles"
weight = 10

[[main]]
name = "Tutoriais"
pageRef = "tutorials"
weight = 20

[[main]]
name = "Notas"
pageRef = "notes"
weight = 30

# [[main]]
#   pre = "github"
#   name = "GitHub"
#   url = "https://github.com/nunocoracao/blowfish"
#   weight = 30

# [[main]]
#   identifier = "github2"
#   pre = "github"
#   url = "https://github.com/nunocoracao/blowfish"
#   weight = 40

# [[footer]]
#   name = "Privacy"
#   url = "https://external-link"
