backend:
  name: github
  repo: zozores/zozores-page
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

i18n:
  structure: multiple_files
  locales: [en, pt-br]
  default_locale: pt-br

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{title | localize}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", i18n: true }
      - { label: "External URL", name: "externalUrl", widget: "string" }
      - { label: "Featured Image", name: "featureimage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", i18n: true }
      - { label: "Categories", name: "categories", widget: "list", i18n: true }
      - { label: "Series", name: "series", widget: "list", i18n: true }
      - { label: "Series Order", name: "series_order", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{title | localize}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", i18n: true }
      - { label: "External URL", name: "externalUrl", widget: "string" }
      - { label: "Featured Image", name: "featureimage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", i18n: true }
      - { label: "Categories", name: "categories", widget: "list", i18n: true }
      - { label: "Series", name: "series", widget: "list", i18n: true }
      - { label: "Series Order", name: "series_order", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }